<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS02_TuongTacVaHoTroNguoiDung</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>bde652c7-62e0-43c0-a5a3-0f9e155d8fbe</testSuiteGuid>
   <testCaseLink>
      <guid>4a89c847-f629-4887-89d0-ead844251c67</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/tuong-tac-ho-tro-nguoi-dung/HTND01_LIenLacQuaForm</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>64adaaa4-8097-4a3e-8260-1baf071caacb</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/tuong-tac-ho-tro-nguoi-dung</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>64adaaa4-8097-4a3e-8260-1baf071caacb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>name</value>
         <variableId>f454b56b-d99b-48ef-8a74-8fe9ced4ce72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>64adaaa4-8097-4a3e-8260-1baf071caacb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>5140807b-0516-4ca8-a3ce-7e8673bdd624</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>64adaaa4-8097-4a3e-8260-1baf071caacb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>subject</value>
         <variableId>6526e9ea-f8ee-4477-a6b2-dd14559183ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>64adaaa4-8097-4a3e-8260-1baf071caacb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>message</value>
         <variableId>abee311b-4b9a-437f-9915-4d53f8a7b3e7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf2b148d-dac4-46f7-b858-ccbc80590d16</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tuong-tac-ho-tro-nguoi-dung/HTND02_TheoDoiTrang</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2ccbf3fd-7d3a-4f16-972f-11ca6b0abb85</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>2-2</value>
         </iterationEntity>
         <testDataId>Data Files/tuong-tac-ho-tro-nguoi-dung</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2ccbf3fd-7d3a-4f16-972f-11ca6b0abb85</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>459f496a-8f88-48e3-922b-fe09274c33d6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c686c403-b0de-4555-8909-6c9169d6db5d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/tuong-tac-ho-tro-nguoi-dung/HTND03_ThemDanhGiaSanPham</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c3d15a4f-64e3-4d99-af7e-8aa046ab83bb</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>3-3</value>
         </iterationEntity>
         <testDataId>Data Files/tuong-tac-ho-tro-nguoi-dung</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>c3d15a4f-64e3-4d99-af7e-8aa046ab83bb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>product</value>
         <variableId>4eac2b5a-c490-4ddb-95c8-7fe6c7abbaaa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c3d15a4f-64e3-4d99-af7e-8aa046ab83bb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>name</value>
         <variableId>f6c3330f-2c01-48e0-92c8-9bfd99ff9066</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c3d15a4f-64e3-4d99-af7e-8aa046ab83bb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>c91aafbb-a266-4070-9bb9-b29116e735e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c3d15a4f-64e3-4d99-af7e-8aa046ab83bb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>review</value>
         <variableId>77bb9e0d-4fbb-479b-8e6c-eff877d051a8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
