<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>aRegisterLogin</name>
   <tag></tag>
   <elementGuidId>f70c60e7-d131-4b63-b751-a28ca12b5a02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p//a[@href='/login']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
